use_frameworks!

target 'UICollectionViewLeftAlignFlowLayout_Example' do
  pod 'UICollectionViewLeftAlignFlowLayout', :path => '../'

  target 'UICollectionViewLeftAlignFlowLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
